# Generated by Django 4.2.7 on 2026-02-21 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('ipfs_cid', models.CharField(max_length=100)),
                ('file_hash', models.CharField(max_length=66)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('encryption_iv', models.CharField(blank=True, max_length=50, null=True)),
                ('record_type', models.CharField(choices=[('lab', 'Lab Results'), ('imaging', 'Imaging & Radiology'), ('prescription', 'Prescription'), ('discharge', 'Discharge Summary'), ('referral', 'Referral Letter'), ('vaccination', 'Immunization Record'), ('ayush', 'AYUSH Record'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_as_patient', to='users.user')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_as_doctor', to='users.user')),
            ],
            options={
                'db_table': 'medical_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
